RAM_LIMIT=# memory limit in B, MB, KB, GB
CPU_LIMIT=# cpu limit in percents (optional, 100% by default)
TIME_LIMIT=# time limit in seconds (optional, no limit by default)
JAIL_DIR=# directory to store container jails
EXE_PATH=# path to the compiled, statically linked executable
STDIN_PATH=# path to redirected stdin file (optional)
STDOUT_PATH=# path to redirected stdout file (optional)
STDERR_PATH=# path to redirected stderr file (optional)
